### ISSUE TITLE
Meter.reset() function not reset totalvolume counter

### ISSUE THREAD

**Issue by AvinashPudale** [sekdiy/FlowMeter#13]
**Meter.reset() function not reset totalvolume counter

**Comment by sekdiy** [comment]
This behaviour is by design, see #1 .

The reset functionality should not void total volume count, because a *meter* should be tamper proof.

If you want to reinitialize the meter, please do so by explicitly setting the values (see #1).

If you think that this should be improved, please give some context and insight.

**Comment by AvinashPudale** [comment]
void FlowMeter::reset() {
    cli();                                                                  //!< going to change interrupt variable(s)
    this->_currentPulses = 0;                                               //!< reset pulse counter
    sei();                                                                  //!< done changing interrupt variable(s)
   **this->_totalVolume = 0.0f;**                                            //just added this line now works as expected 
   this->_currentFrequency = 0.0f;
  i added one line at above fuction now works as expected by me

**Comment by sekdiy** [comment]
Yes, as I mentioned above, this possibility was discussed in #1. 

But do you think this is a feature that's missing in the library?
If so, why?

**Comment by AvinashPudale** [comment]
When we call reset() function in setup function it work like charm. 
 I use reset() function in loop with if statement ,to  trigger relay on or off based on total volume despensed from trigger. 
 Then I  use reset() function. Which  reset all current volume not totalvalume. 
Total volume count remains as privous value.

**Comment by sekdiy** [comment]
Actually, that's what `current volume` is intended for.

The difference between `current volume` and `total volume` is that the former is resettable, the latter is not.
This is by design. 

If you intend to trigger a relay based on volume since last reset, isn't that `current volume`?
In other words: isn't your modification unifying `current` and `total` volumes, just making them identical all the time?

**Comment by sekdiy** [comment]
Closed due to inactivity.
