### ISSUE TITLE
Support for Arduino Uno Wifi Rev2

### ISSUE THREAD

**Issue by SkyScyt** [sekdiy/FlowMeter#22]
Hi Sebastian,

thanks for your work to put this together. 

I am running a hydroponic system in my office growing lettuce based on the Uno Wifi Rev2 with lots of sensors on it. I bought a flowmeter and was happy to find this library. It seems as if its not supporting the Uno Wifi Rev2. When trying to compile your sample sketch in the web editor or also desktop client, me and a friend got the same error on different computers. When we switch to older Arduino versions through Tools->Boards it works. We could not get it to work on our own. Would be great if you would consider supporting the Rev2 or if you could give a hint how to solve it :) 

Best regards
Philipp

**Error Message:**
![Bildschirmfoto 2021-05-07 um 17 41 34](https://user-images.githubusercontent.com/83829826/117474735-86992400-af5b-11eb-8761-6eabb8a36718.png)

**Comment by sekdiy** [comment]
Hi Philipp,

this is a bug in the Arduino Core API for the Uno Wifi Rev2 (and compatible): https://github.com/arduino/ArduinoCore-API/issues/25

You can quickly fix this for your project by patching the file "FlowMeter.cpp" in line 18 as follows:

```diff
-        attachInterrupt(this->_pin, this->_interruptCallback, this->_interruptMode);
+        attachInterrupt(digitalPinToInterrupt(this->_pin), this->_interruptCallback, (PinStatus) this->_interruptMode);
```

The call to `digitalPinToInterrupt()` cares for the fact that the megaAVR-0 chip family can use different pins for interrupts than the traditional ATMega controllers.

The type conversion to `PinStatus` reflects the incompatible change in the Arduino Core API.

Please keep in mind that this patch would need to be reverted in order to go back to the classic Arduino platform.

I'll keep an eye on the issue in order to update this library as soon as a compatible solution has been established.

**Comment by SkyScyt** [comment]
Hi Sebastian,

so cool this works 👍 
Thanks for your look into it and providing a solution so quickly.
