### ISSUE TITLE
problem with library

### ISSUE THREAD

**Issue by Sayed88** [sekdiy/FlowMeter#23]
**Description**
there are a problem with the reset of meter i have a Yf s402 sensor i have make some calibration for it but it in first filling gives required quantity second it is wrong with minus

**Comment by sekdiy** [comment]
Hello,

thanks for reporting the issue.

I'm afraid I need more information in order to understand the nature of the problem.

I understand that you would like to use the `reset` function.
Could you please describe what you would like to achieve and what you have tried so far?

Thanks!

**Comment by sekdiy** [comment]
If you have new information, please reopen this issue.

**Comment by Sayed88** [comment]
Thank you for your respond I am asking you to add more sensors like yf-s402 in your library I can not calibrate it with my tools so I asking you and for the reset problem I have changed the library to reset the total volume and it solve the problem my problem now is the calibration of the yf-s402 sensor what ever I do the library count at first time well then it reduce the volume

**Comment by sekdiy** [comment]
> I am asking you to add more sensors like yf-s402 in your library 

Okay, I see.

Well, unfortunately I can only add sensors that I have available. ;)

> I can not calibrate it with my tools so I asking you 

Perhaps you can send your calibration data set.
I'd be happy to take a look at the parameters and try to make sense of them.

> for the reset problem I have changed the library to reset the total volume and it solve the problem

Yes, that seems to be the preferred solution for everyone who wants to circumvent the metering feature and use the library as a pure sensor driver (see #1). ;)

> what ever I do the library count at first time well then it reduce the volume

I have never experienced this behaviour.

In order to understand what's going on, I really would need more information about your setup (see the issue template):

**Hardware (please complete the following information):**
 - Board type
 - Pins used

**Software (please complete the following information):**
 - OS
 - IDE
 - Other libraries

**Minimal example to reproduce (please complete the following information):**
 - Code to reproduce
 - Wiring to reproduce

Thanks!

**Comment by Sayed88** [comment]
Thank you I will send the data you requested as soon as possible

**Comment by sekdiy** [comment]
If you have new information, please reopen this issue.
